apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repository_name }}
  description: ${{ values.repository_description }}
  annotations:
    github.com/project-slug: ${{ values.repository_owner }}/${{ values.repository_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: ${{ values.catalog_owner }}
  system: ${{ values.catalog_system }}