apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-adr-file
  title: Add ADR File
  description: Creates a docs/adr.md file and opens a PR
  tags:
    - adr-file
spec:
  owner: "group:default/spotify-backstage-trial-team"
  type: template
  lifecycle: experimental

  parameters:
    - title: Provide repository info
      required:
        - repoHost
        - repoOrg
        - repoName
      properties:
        repoHost:
          title: Host
          type: string
          default: github.com
          readOnly: true
        repoOrg:
          title: Organization
          type: string
          default: ONS-Innovation
          readOnly: true
        repoName:
          title: Repository Name
          type: string
          description: Enter the name of the repository

    - title: ADR Options
      properties:
        preFill:
          type: boolean
          title: Pre fill ADR fields
          default: false
        adrFileName:
          type: string
          title: ADR File Name
          description: Name of the ADR markdown file (e.g. adr.md)
          default: adr.md
      dependencies:
        preFill:
          oneOf:
            - properties:
                preFill:
                  const: false
            - required:
                - adrTitle
                - adrStatus
                - adrContext
                - adrDecision
                - adrConsequences
              properties:
                preFill:
                  const: true
                adrTitle:
                  type: string
                  title: ADR Title
                  description: A meaningful title for the decision, without being excessively verbose.
                  default: A meaningful title for the decision.
                adrStatus:
                  type: string
                  title: Status
                  description: What is the status, such as proposed, accepted, rejected, deprecated, superseded, etc.?
                  default: Proposed
                adrContext:
                  type: string
                  title: Context
                  description: What is the issue that we're seeing that is motivating this decision or change?
                  default: Describe the issue...
                adrDecision:
                  type: string
                  title: Decision
                  description: What is the change that we're proposing and/or doing?
                  default: Describe the decision made.
                adrConsequences:
                  type: string
                  title: Consequences
                  description: What becomes easier or more difficult to do because of this change?
                  default: Describe the consequences.
  steps:
    - id: fetch
      name: Fetch repository content
      action: fetch:template
      input:
        url: ./template
        values:
          adr_content: |
            # Architecture Decision Record

            ## Title
            ${{ parameters.adrTitle if parameters.preFill else 'A meaningful title for the decision...' }}

            ## Status
            ${{ parameters.adrStatus if parameters.preFill else 'Proposed' }}

            ## Context
            ${{ parameters.adrContext if parameters.preFill else '[Describe the issue...]' }}

            ## Decision
            ${{ parameters.adrDecision if parameters.preFill else '[Describe the decision made.]' }}

            ## Consequences
            ${{ parameters.adrConsequences if parameters.preFill else '[Describe the consequences.]' }}
        targetPath: docs

    - id: rename
      name: Rename ADR file
      action: fs:rename
      input:
        files:
          - from: docs/adr.md
            to: docs/${{ parameters.adrFileName }}

    - id: pr
      name: Open a PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoHost }}?repo=${{ parameters.repoName }}&owner=${{ parameters.repoOrg }}
        title: "Add ADR file"
        branchName: "add-adr-file"
        description: |
          This PR adds a docs/adr.md file as part of architectural documentation.
        targetPath: "."
        commitMessage: "Add ADR file"
        assignees:
          - ${{ user.entity.metadata.annotations['github.com/user-login'] }}

  output:
    links:
      - title: Open in GitHub
        url: ${{ steps.pr.output.remoteUrl }}
