apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-adr-file
  title: Add ADR File
  description: Creates a docs/adr.md file and opens a PR
  tags:
    - adr-file
spec:
  owner: "group:default/spotify-backstage-trial-team"
  type: template
  lifecycle: experimental

  parameters:
    - title: Provide repository info
      required:
        - repoHost
        - repoOrg
        - repoName
      properties:
        repoHost:
          title: Host
          type: string
          default: github.com
          readOnly: true
        repoOrg:
          title: Organization
          type: string
          default: ONS-Innovation
          readOnly: true
        repoName:
          title: Repository Name
          type: string
          description: Enter the name of the repository

    - title: ADR Options
      properties:
        preFill:
          type: boolean
          title: Pre fill ADR fields
          default: false
      dependencies:
        preFill:
          oneOf:
            - properties:
                preFill:
                  const: false
            - required:
                - adrTitle
                - adrStatus
                - adrContext
                - adrDecision
                - adrConsequences
              properties:
                preFill:
                  const: true
                adrTitle:
                  type: string
                  title: ADR Title
                adrStatus:
                  type: string
                  title: Status
                adrContext:
                  type: string
                  title: Context
                adrDecision:
                  type: string
                  title: Decision
                adrConsequences:
                  type: string
                  title: Consequences

  steps:
    - id: fetch
      name: Fetch repository content
      action: fetch:template
      input:
        url: ./template
        values:
          adr_content: |
            # Architecture Decision Record

            ## Title
            ${{ parameters.adrTitle if parameters.preFill else 'A meaningful title for the decision...' }}

            ## Status
            ${{ parameters.adrStatus if parameters.preFill else 'Proposed' }}

            ## Context
            ${{ parameters.adrContext if parameters.preFill else '[Describe the issue...]' }}

            ## Decision
            ${{ parameters.adrDecision if parameters.preFill else '[Describe the decision made.]' }}

            ## Consequences
            ${{ parameters.adrConsequences if parameters.preFill else '[Describe the consequences.]' }}

    - id: pr
      name: Open a PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoHost }}?repo=${{ parameters.repoName }}&owner=${{ parameters.repoOrg }}
        title: "Add ADR file"
        branchName: "add-adr-file"
        description: |
          This PR adds a docs/adr.md file as part of architectural documentation.
        targetPath: "."
        commitMessage: "Add ADR file"
        assignees: ${{ user.entity.metadata.annotations['github.com/user-login'] }}

  output:
    links:
      - title: Open in GitHub
        url: ${{ steps.pr.output.remoteUrl }}
