apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-adr-file
  title: Add ADR File
  description: Creates a docs/adr.md file and opens a PR
  tags:
    - adr-file
spec:
  owner: "group:default/spotify-backstage-trial-team"
  type: template
  lifecycle: experimental

  parameters:
    - title: Provide repository info
      required:
        - repoHost
        - repoOrg
        - repoName
      properties:
        repoHost:
          title: Host
          type: string
          default: github.com
          readOnly: true
        repoOrg:
          title: Organization
          type: string
          default: ONS-Innovation
          readOnly: true
        repoName:
          title: Repository Name
          type: string
          description: Enter the name of the repository

    - title: Options
      properties:
        preFill:
          type: boolean
          title: Pre fill ADR fields
          default: false
        autoMerge:
          type: boolean
          title: Auto merge PR and register
          default: false

    - title: ADR Details
      if: { properties: { preFill: { const: true } } }
      required: [adrTitle, adrStatus, adrContext, adrDecision, adrConsequences]
      properties:
        adrTitle:
          type: string
          title: ADR Title
        adrStatus:
          type: string
          title: Status
        adrContext:
          type: string
          title: Context
        adrDecision:
          type: string
          title: Decision
        adrConsequences:
          type: string
          title: Consequences

  steps:
    - id: fetch
      name: Fetch repository content
      action: fetch:template
      input:
        url: ./template
        values:
          adr_content: |
            # Architecture Decision Record

            ## Title
            ${{ parameters.adrTitle if parameters.preFill else 'A meaningful title for the decision...' }}

            ## Status
            ${{ parameters.adrStatus if parameters.preFill else 'Proposed' }}

            ## Context
            ${{ parameters.adrContext if parameters.preFill else '[Describe the issue...]' }}

            ## Decision
            ${{ parameters.adrDecision if parameters.preFill else '[Describe the decision made.]' }}

            ## Consequences
            ${{ parameters.adrConsequences if parameters.preFill else '[Describe the consequences.]' }}

    - id: add-catalog-info
      name: Add catalog-info.yaml
      if: ${{ parameters.autoMerge }}
      action: some:action:to:add:catalog-info
      input:
        # ...catalog-info.yaml content...

    - id: pr
      name: Open a PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoHost }}?repo=${{ parameters.repoName }}&owner=${{ parameters.repoOrg }}
        title: "Add ADR file"
        branchName: "add-adr-file"
        description: |
          This PR adds a docs/adr.md file as part of architectural documentation.
        targetPath: "."
        commitMessage: "Add ADR file"

    - id: merge
      name: Auto-merge PR
      if: ${{ parameters.autoMerge }}
      action: github:merge-pull-request
      input:
        pullRequestNumber: ${{ steps.pr.output.pullRequestNumber }}
        repoUrl: ${{ parameters.repoHost }}?repo=${{ parameters.repoName }}&owner=${{ parameters.repoOrg }}

    - id: register
      name: Register the entity
      if: ${{ parameters.autoMerge }}
      action: catalog:register
      input:
        entityRef: ${{ steps.pr.output.remoteUrl }}

  output:
    links:
      - title: Open in GitHub
        url: ${{ steps.pr.output.remoteUrl }}
