apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-adr-file
  title: Add ADR File
  description: Creates a docs/adr.md file and opens a PR
  tags:
    - adr-file
spec:
  owner: "group:default/spotify-backstage-trial-team"
  type: template
  lifecycle: experimental

  parameters:
    - title: Provide repository info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOrganizations:
              - ONS-Innovation

  steps:
    - id: fetch
      name: Fetch repository content
      action: fetch:template
      input:
        url: ./template
        values:
          adr_content: >
            # Architecture Decision Record
            ## Title 
            
            A meaningful title for the decision, without being excessively verbose. 
            
            ## Status 
            
            What is the status, such as proposed, accepted, rejected, deprecated, superseded, etc.? 
            
            ## Context 
            
            What is the issue that we're seeing that is motivating this decision or change? 
            
            ## Decision 
            
            What is the change that we're proposing and/or doing? 
            
            ## Consequences 
            
            What becomes easier or more difficult to do because of this change? 
    - id: pr
      name: Open a PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Add ADR file"
        branchName: "add-adr-file"
        description: |
          This PR adds a docs/adr.md file as part of architectural documentation.
        targetPath: '.'
        commitMessage: "Add ADR file"
    - id: register
      name: Register the entity
      action: catalog:register
      input:
        entityRef: ${{ steps.pr.output.remoteUrl }}
