apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-adr-file
  title: Add ADR File
  description: Creates a docs/adr.md file and opens a PR
  tags:
    - adr-file
spec:
  owner: "group:default/spotify-backstage-trial-team"
  type: template
  lifecycle: experimental

  parameters:
    - title: Provide repository info
      required:
        - repoHost
        - repoOrg
        - repoName
      properties:
        repoHost:
          title: Host
          type: string
          default: github.com
          readOnly: true
        repoOrg:
          title: Organization
          type: string
          default: ONS-Innovation
          readOnly: true
        repoName:
          title: Repository Name
          type: string
          description: Enter the name of the repository

    - title: ADR Options
      properties:
        preFill:
          type: boolean
          title: Pre fill ADR fields
          default: false
        adrFileName:
          type: string
          title: ADR File Name
          description: Name of the ADR markdown file (e.g. adr.md)
          default: adr.md
      dependencies:
        preFill:
          oneOf:
            - properties:
                preFill:
                  const: false
            - required:
                - adrTitle
                - adrStatus
                - adrContext
                - adrDecision
                - adrConsequences
              properties:
                preFill:
                  const: true
                adrTitle:
                  type: string
                  title: ADR Title
                  description: A meaningful title for the decision, without being excessively verbose.
                  default: A meaningful title for the decision.
                adrStatus:
                  type: string
                  title: Status
                  description: What is the status, such as proposed, accepted, rejected, deprecated, superseded, etc.?
                  default: Proposed
                adrContext:
                  type: string
                  title: Context
                  description: What is the issue that we're seeing that is motivating this decision or change?
                  default: Describe the issue...
                adrDecision:
                  type: string
                  title: Decision
                  description: What is the change that we're proposing and/or doing?
                  default: Describe the decision made.
                adrConsequences:
                  type: string
                  title: Consequences
                  description: What becomes easier or more difficult to do because of this change?
                  default: Describe the consequences.
    - title: Catalog Registration
      properties:
        createCatalogInfo:
          title: Create a new catalog-info.yaml?
          type: boolean
          description: "Warning: Only select this if the repo does not have a catalog-info.yaml. This will create a catalog-info.yaml file in the root of the repository. After the PR is merged, you can register the component in the catalog."
          default: false
      dependencies:
        createCatalogInfo:
          oneOf:
            - properties:
                createCatalogInfo:
                  const: false
            - required:
                - repository_name
                - repository_description
                - repository_owner
                - catalog_owner
                - catalog_system
              properties:
                createCatalogInfo:
                  const: true
                repository_name:
                  title: Name
                  type: string
                  description: What is your repository name? (Use hyphens or underscores for readability. Avoid special characters, spaces, or uppercase letters - e.g. my-awesome-project)
                  ui:field: EntityNamePicker
                repository_description:
                  title: Description
                  type: string
                  description: What is your repository description?
                repository_owner:
                  title: Repo Organization
                  type: string
                  description: What is the organization for your repository? (e.g. your GitHub username)
                  default: ONS-Innovation
                catalog_owner:
                  title: Catalog Owner
                  type: string
                  description: Who owns your repository? (user or group)
                  ui:field: OwnerPicker
                  ui:options:
                    catalogFilter:
                      kind: [User, Group]
                catalog_system:
                  title: Catalog System
                  type: string
                  description: Which system is this connected to?
                  ui:field: EntityPicker
                  ui:options:
                    catalogFilter:
                      - kind: System
  steps:
    - id: fetch-adr
      name: Fetch ADR Template
      action: fetch:template
      input:
        url: ./template/docs
        values:
          adr_content: |
            # Architecture Decision Record

            ## Title
            ${{ parameters.adrTitle if parameters.preFill else 'A meaningful title for the decision...' }}

            ## Status
            ${{ parameters.adrStatus if parameters.preFill else 'Proposed' }}

            ## Context
            ${{ parameters.adrContext if parameters.preFill else '[Describe the issue...]' }}

            ## Decision
            ${{ parameters.adrDecision if parameters.preFill else '[Describe the decision made.]' }}

            ## Consequences
            ${{ parameters.adrConsequences if parameters.preFill else '[Describe the consequences.]' }}
        targetPath: ./docs

    - id: rename-adr
      name: Rename ADR file
      action: fs:rename
      input:
        files:
          - from: ./docs/adr_template.md
            to: ./docs/${{ parameters.adrFileName }}

    - id: fetch-catalog-info
      name: Create catalog-info.yaml
      if: ${{ parameters.createCatalogInfo }}
      action: fetch:template
      input:
        url: ./template
        targetPath: ./
        values:
          repository_name: ${{ parameters.repository_name }}
          repository_description: ${{ parameters.repository_description }}
          repository_owner: ${{ parameters.repository_owner }}
          catalog_owner: ${{ parameters.catalog_owner }}
          catalog_system: ${{ parameters.catalog_system }}

    - id: pr
      name: Open a PR
      action: publish:github:pull-request
      input:
        update: true
        repoUrl: ${{ parameters.repoHost }}?repo=${{ parameters.repoName }}&owner=${{ parameters.repoOrg }}
        title: "Backstage: Add ADR file"
        branchName: "add-adr-file"
        description: |
          This PR adds a docs/adr.md file as part of architectural documentation.
          ${{ parameters.createCatalogInfo ? 'Catalog-info.yaml created in the root of the repository.' : '' }}
        targetPath: "."
        commitMessage: "Backstage: Add ADR file"
        assignees:
          - ${{ user.entity.metadata.annotations['github.com/user-login'] }}

  output:
    text:
      - title: "Success!"
        content: |
          Pull request created to add the ADR file to the repository.
          {% if parameters.createCatalogInfo %}
          Catalog-info.yaml created in the root of the repository.
          After the pull request is merged, you can register the component in the catalog.
          Go to /catalog-import to register the component in the catalog.
          {% endif %}
    links:
      - title: Open in GitHub
        url: ${{ steps.pr.output.remoteUrl }}

